# Gives Hilt enough room to build
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8

# Speeds up your build
org.gradle.configuration-cache=true
org.gradle.parallel=true

# Critical fixes for modern libraries
android.useAndroidX=true
android.enableJetifier=true

# Coding standards
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35